### PR TITLE
Final touches

### PR DESCRIPTION
**Pull request by stephenkati**
The main activity was to improve the look and feel of the website using CSS styling.
The following changes were added to achieve that:

- [ ] Adding vibrant colors.
- [ ]Making the website screen responsive.

### CODE REVIEW

**Review by Ibizugbe — CHANGES_REQUESTED** [review]
Hi @stephenkati 👋👋, 

tryagain


Good job so far!👍😉
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅

- [x] App is properly styled with the layout used as a guideline👍
- [x] UI looks great👍
- [x] Gitfloow has been used👍


## Required Changes ♻️

- [ ] Nice work on documenting your project😉 everything about your project looks just great👍 but let's address this little issue😉. Kindly add details about the API you are consuming to your readme😉 This will make your readme more descriptive and give it a more professional look😎

_Check the comments under the review._

## Optional suggestions
- no optional suggestion😎
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Mihndim2020 — APPROVED** [review]
# STATUS: APPROVED!!!  🎉 🎉 🎉 :champagne: :champagne: :champagne:
Hi @stephenkati, 

### Good job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 🎉 🎉 :champagne: :champagne: :champagne:

Congratulations-Memes-FEATURED

## Optional suggestions

_Check the comments under the review._

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack  using this handle @mihndim.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by stephenkati** [comment]
> # STATUS: APPROVED!!!      
> Hi @stephenkati,
> 
> ### Good job !!!
> ### To Highlight!  
> heavy_check_mark Good commit messages heavy_check_mark Descriptive Readme file
> 
> Your project is complete! Great work on making the changes requested by the previous reviewer. There is nothing else to say other than... it's time to merge it :shipit: Congratulations! tada tada tada champagne champagne champagne
> 
> Congratulations-Memes-FEATURED
> 
> ## Optional suggestions
> _Check the comments under the review._
> 
> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
> 
> ### N/A
> Cheers and Happy coding!clapclapclap
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can get to me on slack using this handle @Mihndim.
> 
> _As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

Thank you, @Mihndim2020

**Comment by stephenkati** [comment]
Thank you, @Mihndim2020

**Pull request merged**
